include: package:lint/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: true
    sort_pub_dependencies: false
    prefer_const_literals_to_create_immutables: false

    # web false
    avoid_web_libraries_in_flutter: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"